<a href="https://colab.research.google.com/github/IngridRodrigues15/study_dataset_iris/blob/main/machine_learning_dataset_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Referencias 

Reproduzir os resultados do treinamento e avaliação de modelos conforme apresentado no capítulo 5 da referência presente no seguinte repositório (arquivo Moving2DS_Part1_pt_br.pdf).


https://github.com/alex-carneiro/Moving2DS

In [ ]:
import pandas as pd
import numpy as np

# lib para algoritmo de regressão linear
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import joblib

import matplotlib.pyplot as plt
%matplotlib inline


In [ ]:
# Carregando o data set

dataset = pd.read_csv("/content/iris.data", header=None)
dataset.columns = ["sepal_l", "sepal_w",
                   "petal_l", "petal_w",
                   "class"]

print("Read %d samples from the dataset"%len(dataset))
dataset.sample(5)

Read 150 samples from the dataset


sepal_l  sepal_w  petal_l  petal_w            class
0        5.1      3.5      1.4      0.2      Iris-setosa
43       5.0      3.5      1.6      0.6      Iris-setosa
113      5.7      2.5      5.0      2.0   Iris-virginica
30       4.8      3.1      1.6      0.2      Iris-setosa
53       5.5      2.3      4.0      1.3  Iris-versicolor

In [ ]:
#Data split for training and testing

full_data_input = dataset[["sepal_l", "sepal_w",
                           "petal_l", "petal_w"]].values

# print(full_data_input)

full_data_output = dataset["class"].values
# print(full_data_output)



train_input, test_input,\
train_output, test_output = train_test_split(full_data_input,
                                             full_data_output,
                                             test_size=.1)
full_data_input.shape, train_input.shape, test_input.shape

((150, 4), (135, 4), (15, 4))

In [ ]:

# Create and train a new instance of the classifier

model = LogisticRegression()
model.fit(train_input, train_output)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
# Evaluate the trained model

acc = model.score(test_input, test_output)
print("Model accuracy = %.1f%%"%(100 * acc))

Model accuracy = 100.0%


Curiosidadee, usando apenas 10% dos dados, a acuracia chega a 100%, aumentando o volume de dados a acuracia vai diminuindo 

In [ ]:
predictions = model.predict(test_input)
matrix = confusion_matrix(predictions, test_output)
print(matrix)

[[13  0  0]
 [ 0  9  0]
 [ 0  1  7]]


In [ ]:

classes = sorted(np.unique(test_output))
pd.DataFrame(dict([(cl, l) for cl, l in zip(classes, matrix.T)]), index=classes)

Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               13                0               0
Iris-versicolor            0                9               0
Iris-virginica             0                1               7